src/java/kz/bestsales/common/model/AbstractModel.java
package kz.bestsales.common.model;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import java.io.StringWriter;

/**
 * Created by shef on 25.02.2015.
 */
public abstract class AbstractModel  {

    public String toXml() {
        String modelXML = "";
        try {
            StringWriter sw = new StringWriter();
            JAXBContext jaxbContext = JAXBContext.newInstance(this.getClass());
            Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
            jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
            jaxbMarshaller.marshal(this, sw);
            modelXML = sw.toString().replace("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>", "").replace("\n", "");
        } catch (JAXBException e) {
            e.printStackTrace();
        }
        return modelXML;
    }
}

src/java/kz/bestsales/common/controller/LanguageController.java
package kz.bestsales.common.controller;

/**
 * Created by shef on 26.02.2015.
 */
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

@ManagedBean(name="language")
@SessionScoped
public class LanguageController implements Serializable{

    private static final long serialVersionUID = 1L;

    private String localeCode;

    private static Map<String,Object> countries;
    static{
        Locale locale_ru = new Locale("ru", "RU");
        Locale locale_kz = new Locale("kz", "KZ");
        countries = new LinkedHashMap<String,Object>();
        countries.put("English", Locale.ENGLISH); //label, value
        countries.put("Russian", locale_ru);
        countries.put("Kazakh", locale_kz);
    }

    public Map<String, Object> getCountriesInMap() {
        return countries;
    }


    public String getLocaleCode() {
        return localeCode;
    }


    public void setLocaleCode(String localeCode) {
        this.localeCode = localeCode;
    }

    //value change event listener
    public void countryLocaleCodeChanged(ValueChangeEvent e){
        System.out.println("changed");
        String newLocaleValue = e.getNewValue().toString();

        //loop country map to compare the locale code
        for (Map.Entry<String, Object> entry : countries.entrySet()) {

            if(entry.getValue().toString().equals(newLocaleValue)){
                System.out.println((Locale)entry.getValue());
                FacesContext.getCurrentInstance()
                        .getViewRoot().setLocale((Locale)entry.getValue());

            }
        }
    }

}

src/java/kz/bestsales/common/controller/SenderMailController.java
package kz.bestsales.common.controller;

import javax.faces.bean.ManagedBean;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.io.Serializable;
import java.util.Properties;

@ManagedBean
public class SenderMailController implements Serializable {
    private static final long serialVersionUID = 1L;

    private String username;
    private String password;
    private String to;
    private String subject;
    private String content;

    public SenderMailController() {
    }

    public SenderMailController(String username, String password, String to, String subject, String content) {
        this.username = username;
        this.password = password;
        this.to = to;
        this.subject = subject;
        this.content = content;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void sendMail() {
        // Setup mail server
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        // Get the default Session object.
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("bestsales@info.kz"));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(this.to));
            message.setSubject(this.subject);
            message.setContent(this.content, "text/html; charset=utf-8");
            Transport.send(message);

            System.out.println("Done");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }
}

src/main/webapp/template/common/commonHeader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

<h:body>
    <ui:composition>

        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="row row-centered">
                    <div class="col-xs-6 col-sm-2 ">
                        <div class="navbar-header vcenter">
                            <button id="hidden_menu" type="button" class="navbar-toggle collapsed">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand vcenter child" href="#">Brand</a>
                        </div>
                    </div>

                    <div class="col-xs-6 col-sm-6 ">
                        <div class="navbar-collapse collapse">
                            <h:form id="mainSearch" class="navbar-form " role="search">
                                <div class="form-group input-group ">
								<span id="searchInfoPopover" class="input-group-addon">
																<i class="glyphicon glyphicon-info-sign"></i>
								</span>
                                    <h:inputText id="search" class="form-control"/>

                                    <div class="input-group-btn ">
                                        <button id="searchParam"
                                                class="btn btn-default dropdown-toggle">#{msg['kz.bestsales.index.top.dropdown.text']}<span
                                                class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><input type="checkbox" id="DRESS" name="sales" value="true"/><label
                                                    for="DRESS">#{msg['kz.bestsales.index.top.dropdown.option.first.text']}</label>
                                            </li>
                                            <li><input type="checkbox" id="BOOT" name="sales" value="true"/><label
                                                    for="BOOT">#{msg['kz.bestsales.index.top.dropdown.option.second.text']}</label>
                                            </li>
                                            <li><input type="checkbox" id="ACCSESSORIES" name="sales"
                                                       value="true"/><label
                                                    for="ACCSESSORIES">#{msg['kz.bestsales.index.top.dropdown.option.third.text']}</label>
                                            </li>
                                            <li class="divider"></li>
                                            <li><input type="checkbox" id="SALES" name="sales" value="true"/><label
                                                    for="SALES"
                                                    style="color: red;">#{msg['kz.bestsales.index.top.dropdown.option.sales.text']}</label>
                                            </li>
                                        </ul>
                                    </div>
                                </div>

                                <button type="submit"
                                        class="btn btn-default ">#{msg['kz.bestsales.index.top.button.search.text']}</button>
                            </h:form>
                        </div>
                    </div>

                    <div class="col-xs-4 col-sm-4">
                        <div class="navbar-collapse collapse">
                            <h:form class="navbar-form" role="form">
                                <div class="form-group">
                                    <button id="logRegModal" class="btn btn-primary" type="button">
                                        <span class="glyphicon glyphicon-log-in"> </span>
                                        #{msg['kz.bestsales.index.top.sign.btn.val']}
                                    </button>
                                    <button type="button" class="btn btn-primary"><span
                                            class="glyphicon glyphicon-shopping-cart"> </span>
                                        #{msg['kz.bestsales.index.top.basket.btn.val']}
                                    </button>
                                </div>
                                <h:selectOneMenu value="#{language.localeCode}" onchange="submit()"
                                                 valueChangeListener="#{language.countryLocaleCodeChanged}">
                                    <f:selectItems value="#{language.countriesInMap}" />
                                </h:selectOneMenu>
                            </h:form>

                        </div>
                    </div>
                </div>
                <!--/.row -->
            </div>
        </div>

    </ui:composition>
</h:body>
</html>

src/main/webapp/template/common/commonLayout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

<h:head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <link href="#{request.contextPath}/resources/bootstrap-3.3.2-dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="#{request.contextPath}/resources/bootstrap-3.3.2-dist/css/styles.css" rel="stylesheet"/>
    <link href="#{request.contextPath}/resources/bootstrap-3.3.2-dist/css/dropdown-enhancement.css" rel="stylesheet"/>
</h:head>
<h:body>
    <div id="page">
        <div id="header">
            <ui:insert name="header">
                <ui:include src="commonHeader.xhtml" />
            </ui:insert>
        </div>
        <div id="content">
            <ui:insert name="content">

            </ui:insert>
        </div>
        <div id="footer">
            <ui:insert name="footer">
                <ui:include src="commonFooter.xhtml" />
            </ui:insert>
        </div>
    </div>
</h:body>
</html>